version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}


  app:
    image: project-final-master-app:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jira
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
        - "db.username=${DB_USERNAME}"
        - "db.password=${DB_PASSWORD}"
        - "oauth2.github.client-id=${GITHUB_CLIENT_ID}"
        - "oauth2.github.client-secret=${GITHUB_CLIENT_SECRET}"
        - "oauth2.google.client-id=${GOOGLE_CLIENT_ID}"
        - "oauth2.google.client-secret=${GOOGLE_CLIENT_SECRET}"
        - "oauth2.gitlab.client-id=${GITLAB_CLIENT_ID}"
        - "oauth2.gitlab.client-secret=${GITLAB_CLIENT_SECRET}"
        - "mail.username=${MAIL_USERNAME}"
        - "mail.password=${MAIL_PASSWORD}"


    build:
      context: /
      dockerfile: Dockerfile

